[package]
name = "bevy_epitech"
version = "0.1.0"
edition = "2021"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

[dependencies]
bevy = "0.15.0"

[lints.rust]
unused_imports = "allow"